In [16]:
from scipy.sparse import identity
import numpy as np
from scipy import sparse
from scipy.sparse import lil_matrix
def multicx(L,n):
    sx = lil_matrix([[0,1],[1,0]])
    A = lil_matrix((2**L, 2**L))
    A[:(2**L)-2**(L-n), :(2**L)-2**(L-n)] = identity((2**L)-2**(L-n))
    print(np.array(identity(2**(L-n-1)).A).shape)
    print(np.array(A[:(2**L)-2**(L-n),:(2**L)-2**(L-n)].A).shape)
    A[(2**L)-2**(L-n):,(2**L)-2**(L-n):] = sparse.kron(identity(2**(L-n-1)), sx)
    return A
#print(multicx(3,2).A)

def Revmulticx(L,n):
    sx = lil_matrix([[0,1],[1,0]])
    A = lil_matrix((2**L, 2**L))
    A[:2**(L-n), :2**(L-n)] = sparse.kron(identity(2**(L-n-1)),sx)
    A[2**(L-n):,2**(L-n):] = identity((2**L)-2**(L-n))
    return A
#print("Reversed: \n", Revmulticx(3,2).A)

(1, 1)
(6, 6)
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
Reversed: 
 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#gates
G1 = sparse.kron(multicx(16,4), identity(2**4))
G2 = sparse.kron(identity(2**4),sparse.kron(multicx(13,4), identity(2**3)))
G3 = sparse.kron(identity(2**8),sparse.kron(multicx(10,3), identity(2**2)))
G4 = sparse.kron(identity(2**11),sparse.kron(multicx(8,3), identity(2**1)))
G5 = sparse.kron(identity(2**15),multicx(5,3))
G6 = sparse.kron(identity(2**14), Revmulticx(6,2))

In [8]:
Out_state = G1*(G2*(G3*(G4*(G5*(G6*(G5*(G4*(G3*(G2*G1)))))))))

[array([3, 4]), array([1, 2])]
