In [16]:
from scipy.sparse import identity
import numpy as np
from scipy import sparse
from scipy.sparse import lil_matrix
import scipy.sparse.linalg

In [11]:
mtx = sparse.lil_matrix((4, 5))

In [12]:
from numpy.random import rand
data = np.round(rand(2, 3))

In [13]:
mtx[:2, [1, 2, 3]] = data

In [14]:
print(mtx)

  (0, 1)	1.0
  (0, 2)	1.0
  (1, 1)	1.0
  (1, 3)	1.0


In [38]:
a = np.matrix([[1,0,1],[1,0,1],[2,0,1]])

In [39]:
a_s = sparse.csr_matrix(a)

In [40]:
print(a_s)

  (0, 0)	1
  (0, 2)	1
  (1, 0)	1
  (1, 2)	1
  (2, 0)	2
  (2, 2)	1


In [41]:
b = np.matrix([[1,2,0],[0,0,3],[0,0,1]])
b_s = sparse.csr_matrix(b)

In [88]:
print((a_s*b_s).A)

[[1 2 1]
 [1 2 1]
 [2 4 1]]


In [51]:
np.matmul(a,b)

matrix([[1, 2, 1],
        [1, 2, 1],
        [2, 4, 1]])

# Hadamard test

In [65]:
N = 3

In [63]:
def Hadamard_gate(): # Hadamad gate acting on one qubit.
    
    return 1/np.sqrt(2)*np.array([[1,1],[1,-1]])

def Hadamard(Qubit): 

    '''

    List below will hold gates acting on one qubit. For example, for L = 3,
    the Hadamard gate acting on the qubit 1 is given by = 1 x H x 1, where 
    x is the Kronecker product. Then, qubits_list = [1,H,1].

    ''' 

    qubits_list = [] 
    
    for i in range(N):
        
        if i == Qubit: # Qubit^th position in the list is H.
            
            qubits_list.append(Hadamard_gate())
            
        else: # Other gates are identity operators.
            
            qubits_list.append(np.identity(2))

    '''
    
    The following loop performs the Kronecker product.

    '''        
    
    M = sparse.csr_matrix(qubits_list[0]) # Initializes the final matrix.
    
    for g in range(1,len(qubits_list)):
        
        M = sparse.kron(qubits_list[g],M) # kronecker product.
        
    return M

# RZ gate

In [72]:
N = 2
def Rz_matrix(theta):

    return np.matrix([[np.exp(-1j*theta/2),0],[0,np.exp(1j*theta/2)]])

def Rz(Angle, Qubit):
    
    if Qubit > N -1 :
        
        print("Qubit number exceeds N")
        
    else:    
    
        qubits_list = []
    
        for i in range(N):
        
            if i == Qubit:
            
                qubits_list.append(Rz_matrix(Angle))
            
            else:
            
                qubits_list.append(np.matrix(np.identity(2)))
    
        M = sparse.csr_matrix(qubits_list[0])
    
        for g in range(1,len(qubits_list)):
        
            M = sparse.kron(qubits_list[g], M) # kronecker product.
        
        return M

# Grover reconstructed

In [82]:
def Grover_reconstructed(epsilon):
    

    #Rz_Noise = 2*(np.random.rand(Rz_Number)-0.5)
    ## Initializing the oracle U_w as an identity matrix.
    
    Or = identity(2**N) 

    ## In the following loop we multiply all the 1 and 2 qubit gates with (or without) noise.
    
    j = 0 # Index for the random noise list.
    
    for i in range(len(gates_list)): # l is the list with all the gates.
    
        if gates_list[i][0] == 'rz':
            
            Rz_s = sparse.csr_matrix(Rz(float(gates_list[i][1])  +

                 epsilon * Rz_Noise[j], int(gates_list[i][2])))
            
            Or = Or.multiply(Rz_s)
            
            j = j + 1
        
        elif gates_list[i][0] == 'h':
        
            Hs = sparse.csr_matrix(Hadamard(int(gates_list[i][2])))
            Or = Or.multiply(Hs)
        
        elif gates_list[i][0] == 'cx':
        
            CNOTs = sparse.csr_matrix(CNOT(int(gates_list[i][1]), int(gates_list[i][2])))
            Or = Or.multiply(CNOTs)
     
    Or = Or.todense()
    ## In the following we will fix the phase of the reconstructed Oracle.
    # First we will make all the elements
    # 1 or -1.
    Or = Or/Or[0,0]
    
    ## The sign of the reconstructed Oracle should be same as that of original U_w.
    if np.sign(Or[0,0]) == np.sign(U_w[0,0]):
        
        pass # If the sign is same, then pass.
    
    else:
        
        Or = -Or # Otherwise change the sign.
    Gr = np.matmul(Or, U_s) ## The Grover operator G = U_w * U_s.
    
    return Gr

In [77]:
m = identity(3)
print(m)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
